<?php

namespace Container6T4QHlm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I2xFiKQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.i2xFiKQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.i2xFiKQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'request' => ['privates', '.errored._SF7T.F', NULL, 'Cannot determine controller argument for "App\\Controller\\SortieController::index()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\Request". Did you forget to add a use statement?'],
            'sortieRepository' => ['privates', 'App\\Repository\\SortieRepository', 'getSortieRepositoryService', true],
        ], [
            'manager' => '?',
            'request' => '?',
            'sortieRepository' => 'App\\Repository\\SortieRepository',
        ]);
    }
}
