<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4555QLt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4555QLt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4555QLt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4555QLt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4555QLt\App_KernelDevDebugContainer([
    'container.build_hash' => '4555QLt',
    'container.build_id' => '3b3c2e47',
    'container.build_time' => 1654884138,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4555QLt');
